  language: python
  sudo: required
  python:
    - "3.6"
  script:
    - pip install starred
    - starred --username maguowei --sort > README.md
    - git config --global user.email "travis@travis-ci.org"
    - git config --global user.name "Travis Worker"
    - git checkout master
    - git add README.md
    - git commit -m "Refresh from Travis" -m "[ci skip]"
    - git remote set-url origin https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}
    - git push --quiet origin